version: "2"
services: 
  portainer:
    restart: always
    container_name: portainer
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/portainer:/data
    labels:
      - traefik.port=9000
      - traefik.backend=portainer
  traefik:
    restart: always
    container_name: traefik
    image: traefik
    command: --web --docker --docker.domain=omshome.ga --loglevel=DEBUG
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    labels:
      - traefik.port=8080
      - traefik.backend=traefik